// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/webhook/v1/service.proto

package webhookv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/google/gnostic/openapiv3"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeliveryAttemptStatus int32

const (
	// Delivery attempt is unspecified (default, don't use)
	DeliveryAttemptStatus_DELIVERY_ATTEMPT_STATUS_UNSPECIFIED DeliveryAttemptStatus = 0
	// Delivery attempt is queued
	DeliveryAttemptStatus_DELIVERY_ATTEMPT_STATUS_QUEUED DeliveryAttemptStatus = 1
	// Delivery attempt is in flight
	DeliveryAttemptStatus_DELIVERY_ATTEMPT_STATUS_IN_FLIGHT DeliveryAttemptStatus = 2
	// Delivery attempt was successful
	DeliveryAttemptStatus_DELIVERY_ATTEMPT_STATUS_DELIVERED DeliveryAttemptStatus = 3
	// Delivery attempt failed
	DeliveryAttemptStatus_DELIVERY_ATTEMPT_STATUS_FAILED DeliveryAttemptStatus = 4
	// Delivery attempt was dead-lettered
	DeliveryAttemptStatus_DELIVERY_ATTEMPT_STATUS_DEAD_LETTERED DeliveryAttemptStatus = 5
)

// Enum value maps for DeliveryAttemptStatus.
var (
	DeliveryAttemptStatus_name = map[int32]string{
		0: "DELIVERY_ATTEMPT_STATUS_UNSPECIFIED",
		1: "DELIVERY_ATTEMPT_STATUS_QUEUED",
		2: "DELIVERY_ATTEMPT_STATUS_IN_FLIGHT",
		3: "DELIVERY_ATTEMPT_STATUS_DELIVERED",
		4: "DELIVERY_ATTEMPT_STATUS_FAILED",
		5: "DELIVERY_ATTEMPT_STATUS_DEAD_LETTERED",
	}
	DeliveryAttemptStatus_value = map[string]int32{
		"DELIVERY_ATTEMPT_STATUS_UNSPECIFIED":   0,
		"DELIVERY_ATTEMPT_STATUS_QUEUED":        1,
		"DELIVERY_ATTEMPT_STATUS_IN_FLIGHT":     2,
		"DELIVERY_ATTEMPT_STATUS_DELIVERED":     3,
		"DELIVERY_ATTEMPT_STATUS_FAILED":        4,
		"DELIVERY_ATTEMPT_STATUS_DEAD_LETTERED": 5,
	}
)

func (x DeliveryAttemptStatus) Enum() *DeliveryAttemptStatus {
	p := new(DeliveryAttemptStatus)
	*p = x
	return p
}

func (x DeliveryAttemptStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeliveryAttemptStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_webhook_v1_service_proto_enumTypes[0].Descriptor()
}

func (DeliveryAttemptStatus) Type() protoreflect.EnumType {
	return &file_api_webhook_v1_service_proto_enumTypes[0]
}

func (x DeliveryAttemptStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeliveryAttemptStatus.Descriptor instead.
func (DeliveryAttemptStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_webhook_v1_service_proto_rawDescGZIP(), []int{0}
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_api_webhook_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_webhook_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_api_webhook_v1_service_proto_rawDescGZIP(), []int{0}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_api_webhook_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_webhook_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_api_webhook_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// An endpoint is a URL that receives webhook events
type Endpoint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique ID for the endpoint
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// ID for the tenant
	TenantId string `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Target URL that we will send events to
	Url string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	// Created at timestamp (must be after 2025-01-01 00:00:00 UTC)
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Endpoint) Reset() {
	*x = Endpoint{}
	mi := &file_api_webhook_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Endpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endpoint) ProtoMessage() {}

func (x *Endpoint) ProtoReflect() protoreflect.Message {
	mi := &file_api_webhook_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endpoint.ProtoReflect.Descriptor instead.
func (*Endpoint) Descriptor() ([]byte, []int) {
	return file_api_webhook_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *Endpoint) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Endpoint) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Endpoint) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Endpoint) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// A subscription is a relationship between an endpoint and an event type
type Subscription struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique ID for the subscription
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// ID for the tenant
	TenantId string `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Event type that this subscription is for
	EventType string `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	// Endpoint ID that this subscription is a member of
	EndpointId string `protobuf:"bytes,4,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	// Created at timestamp (must be after 2025-01-01 00:00:00 UTC)
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscription) Reset() {
	*x = Subscription{}
	mi := &file_api_webhook_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription) ProtoMessage() {}

func (x *Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_api_webhook_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription.ProtoReflect.Descriptor instead.
func (*Subscription) Descriptor() ([]byte, []int) {
	return file_api_webhook_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *Subscription) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Subscription) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Subscription) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *Subscription) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *Subscription) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// Create endpoint request message
type CreateEndpointRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID for the tenant
	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Target URL that we will send events to, e.g. http://fake-receiver:8081/hook
	Url string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	// Optional secret. If empty, server generates a secret for you
	Secret        string `protobuf:"bytes,3,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEndpointRequest) Reset() {
	*x = CreateEndpointRequest{}
	mi := &file_api_webhook_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEndpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEndpointRequest) ProtoMessage() {}

func (x *CreateEndpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_webhook_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEndpointRequest.ProtoReflect.Descriptor instead.
func (*CreateEndpointRequest) Descriptor() ([]byte, []int) {
	return file_api_webhook_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *CreateEndpointRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateEndpointRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CreateEndpointRequest) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

// Create endpoint response message
type CreateEndpointResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The newly created endpoint
	Endpoint      *Endpoint `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEndpointResponse) Reset() {
	*x = CreateEndpointResponse{}
	mi := &file_api_webhook_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEndpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEndpointResponse) ProtoMessage() {}

func (x *CreateEndpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_webhook_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEndpointResponse.ProtoReflect.Descriptor instead.
func (*CreateEndpointResponse) Descriptor() ([]byte, []int) {
	return file_api_webhook_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *CreateEndpointResponse) GetEndpoint() *Endpoint {
	if x != nil {
		return x.Endpoint
	}
	return nil
}

// Create subscription request message
type CreateSubscriptionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tenant ID for the subscription
	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Event type that this subscription is for
	EventType string `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	// Endpoint ID that this subscription is a member of
	EndpointId    string `protobuf:"bytes,3,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSubscriptionRequest) Reset() {
	*x = CreateSubscriptionRequest{}
	mi := &file_api_webhook_v1_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubscriptionRequest) ProtoMessage() {}

func (x *CreateSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_webhook_v1_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*CreateSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_api_webhook_v1_service_proto_rawDescGZIP(), []int{6}
}

func (x *CreateSubscriptionRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateSubscriptionRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *CreateSubscriptionRequest) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

// Create subscription response message
type CreateSubscriptionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The newly created subscription
	Subscription  *Subscription `protobuf:"bytes,1,opt,name=subscription,proto3" json:"subscription,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSubscriptionResponse) Reset() {
	*x = CreateSubscriptionResponse{}
	mi := &file_api_webhook_v1_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubscriptionResponse) ProtoMessage() {}

func (x *CreateSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_webhook_v1_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*CreateSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_api_webhook_v1_service_proto_rawDescGZIP(), []int{7}
}

func (x *CreateSubscriptionResponse) GetSubscription() *Subscription {
	if x != nil {
		return x.Subscription
	}
	return nil
}

// Publish event request message
type PublishEventRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID for the tenant
	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Event type to be published
	EventType string `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	// Payload data for the event (arbitrary JSON)
	Payload *structpb.Struct `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	// Required for deduplication, if empty, no dedup
	IdempotencyKey string `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PublishEventRequest) Reset() {
	*x = PublishEventRequest{}
	mi := &file_api_webhook_v1_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishEventRequest) ProtoMessage() {}

func (x *PublishEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_webhook_v1_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishEventRequest.ProtoReflect.Descriptor instead.
func (*PublishEventRequest) Descriptor() ([]byte, []int) {
	return file_api_webhook_v1_service_proto_rawDescGZIP(), []int{8}
}

func (x *PublishEventRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *PublishEventRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *PublishEventRequest) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PublishEventRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

// Publish event response message
type PublishEventResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Event ID
	EventId string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// How many deliveries for this event are enqueued
	FanoutCount   int32 `protobuf:"varint,2,opt,name=fanout_count,json=fanoutCount,proto3" json:"fanout_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishEventResponse) Reset() {
	*x = PublishEventResponse{}
	mi := &file_api_webhook_v1_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishEventResponse) ProtoMessage() {}

func (x *PublishEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_webhook_v1_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishEventResponse.ProtoReflect.Descriptor instead.
func (*PublishEventResponse) Descriptor() ([]byte, []int) {
	return file_api_webhook_v1_service_proto_rawDescGZIP(), []int{9}
}

func (x *PublishEventResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *PublishEventResponse) GetFanoutCount() int32 {
	if x != nil {
		return x.FanoutCount
	}
	return 0
}

type DeliveryAttempt struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique ID for the delivery attempt
	DeliveryId string `protobuf:"bytes,1,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"`
	// ID of the event being delivered
	EventId string `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// ID of the endpoint being delivered to
	EndpointId string `protobuf:"bytes,3,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	// link to source attempt (if replayed)
	ReplayOf string `protobuf:"bytes,4,opt,name=replay_of,json=replayOf,proto3" json:"replay_of,omitempty"`
	// queued|inflight|delivered|failed|dead
	Status DeliveryAttemptStatus `protobuf:"varint,5,opt,name=status,proto3,enum=api.webhook.v1.DeliveryAttemptStatus" json:"status,omitempty"`
	// HTTP status code
	HttpStatus int32 `protobuf:"varint,6,opt,name=http_status,json=httpStatus,proto3" json:"http_status,omitempty"`
	// Optional error reason
	ErrorReason string `protobuf:"bytes,7,opt,name=error_reason,json=errorReason,proto3" json:"error_reason,omitempty"`
	// Timestamp of when the delivery was enqueued
	EnqueuedAt *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=enqueued_at,json=enqueuedAt,proto3" json:"enqueued_at,omitempty"`
	// Timestamp of when the delivery was dequeued
	DequeuedAt *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=dequeued_at,json=dequeuedAt,proto3" json:"dequeued_at,omitempty"`
	// Timestamp of when the delivery was sent
	SentAt *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	// Timestamp of when the delivery was delivered
	DeliveredAt *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=delivered_at,json=deliveredAt,proto3" json:"delivered_at,omitempty"`
	// Timestamp of when the delivery failed
	FailedAt *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=failed_at,json=failedAt,proto3" json:"failed_at,omitempty"`
	// Timestamp of when the delivery was dead-lettered
	DlqAt         *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=dlq_at,json=dlqAt,proto3" json:"dlq_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryAttempt) Reset() {
	*x = DeliveryAttempt{}
	mi := &file_api_webhook_v1_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryAttempt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryAttempt) ProtoMessage() {}

func (x *DeliveryAttempt) ProtoReflect() protoreflect.Message {
	mi := &file_api_webhook_v1_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryAttempt.ProtoReflect.Descriptor instead.
func (*DeliveryAttempt) Descriptor() ([]byte, []int) {
	return file_api_webhook_v1_service_proto_rawDescGZIP(), []int{10}
}

func (x *DeliveryAttempt) GetDeliveryId() string {
	if x != nil {
		return x.DeliveryId
	}
	return ""
}

func (x *DeliveryAttempt) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *DeliveryAttempt) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *DeliveryAttempt) GetReplayOf() string {
	if x != nil {
		return x.ReplayOf
	}
	return ""
}

func (x *DeliveryAttempt) GetStatus() DeliveryAttemptStatus {
	if x != nil {
		return x.Status
	}
	return DeliveryAttemptStatus_DELIVERY_ATTEMPT_STATUS_UNSPECIFIED
}

func (x *DeliveryAttempt) GetHttpStatus() int32 {
	if x != nil {
		return x.HttpStatus
	}
	return 0
}

func (x *DeliveryAttempt) GetErrorReason() string {
	if x != nil {
		return x.ErrorReason
	}
	return ""
}

func (x *DeliveryAttempt) GetEnqueuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EnqueuedAt
	}
	return nil
}

func (x *DeliveryAttempt) GetDequeuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DequeuedAt
	}
	return nil
}

func (x *DeliveryAttempt) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

func (x *DeliveryAttempt) GetDeliveredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeliveredAt
	}
	return nil
}

func (x *DeliveryAttempt) GetFailedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FailedAt
	}
	return nil
}

func (x *DeliveryAttempt) GetDlqAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DlqAt
	}
	return nil
}

type GetDeliveryStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the event to check deliveries for
	EventId string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// ID of the endpoint to check deliveries for
	EndpointId string `protobuf:"bytes,2,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	// Start datetime to search
	From *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	// End datetime to search
	To *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`
	// Limit the number of results (default 10)
	Limit         int32 `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeliveryStatusRequest) Reset() {
	*x = GetDeliveryStatusRequest{}
	mi := &file_api_webhook_v1_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeliveryStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeliveryStatusRequest) ProtoMessage() {}

func (x *GetDeliveryStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_webhook_v1_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeliveryStatusRequest.ProtoReflect.Descriptor instead.
func (*GetDeliveryStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_webhook_v1_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetDeliveryStatusRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *GetDeliveryStatusRequest) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *GetDeliveryStatusRequest) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *GetDeliveryStatusRequest) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *GetDeliveryStatusRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetDeliveryStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of delivery attempts
	Attempts      []*DeliveryAttempt `protobuf:"bytes,1,rep,name=attempts,proto3" json:"attempts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeliveryStatusResponse) Reset() {
	*x = GetDeliveryStatusResponse{}
	mi := &file_api_webhook_v1_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeliveryStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeliveryStatusResponse) ProtoMessage() {}

func (x *GetDeliveryStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_webhook_v1_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeliveryStatusResponse.ProtoReflect.Descriptor instead.
func (*GetDeliveryStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_webhook_v1_service_proto_rawDescGZIP(), []int{12}
}

func (x *GetDeliveryStatusResponse) GetAttempts() []*DeliveryAttempt {
	if x != nil {
		return x.Attempts
	}
	return nil
}

type ReplayDeliveryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the delivery to replay
	DeliveryId string `protobuf:"bytes,1,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"`
	// Optional reason for replaying the delivery
	Reason        string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayDeliveryRequest) Reset() {
	*x = ReplayDeliveryRequest{}
	mi := &file_api_webhook_v1_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayDeliveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayDeliveryRequest) ProtoMessage() {}

func (x *ReplayDeliveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_webhook_v1_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayDeliveryRequest.ProtoReflect.Descriptor instead.
func (*ReplayDeliveryRequest) Descriptor() ([]byte, []int) {
	return file_api_webhook_v1_service_proto_rawDescGZIP(), []int{13}
}

func (x *ReplayDeliveryRequest) GetDeliveryId() string {
	if x != nil {
		return x.DeliveryId
	}
	return ""
}

func (x *ReplayDeliveryRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ReplayDeliveryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The newly enqueued attempt
	NewAttempt    *DeliveryAttempt `protobuf:"bytes,1,opt,name=new_attempt,json=newAttempt,proto3" json:"new_attempt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayDeliveryResponse) Reset() {
	*x = ReplayDeliveryResponse{}
	mi := &file_api_webhook_v1_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayDeliveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayDeliveryResponse) ProtoMessage() {}

func (x *ReplayDeliveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_webhook_v1_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayDeliveryResponse.ProtoReflect.Descriptor instead.
func (*ReplayDeliveryResponse) Descriptor() ([]byte, []int) {
	return file_api_webhook_v1_service_proto_rawDescGZIP(), []int{14}
}

func (x *ReplayDeliveryResponse) GetNewAttempt() *DeliveryAttempt {
	if x != nil {
		return x.NewAttempt
	}
	return nil
}

type ListDLQRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the endpoint to filter by
	EndpointId string `protobuf:"bytes,1,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	// Limit the number of results (default 10)
	Limit         int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDLQRequest) Reset() {
	*x = ListDLQRequest{}
	mi := &file_api_webhook_v1_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDLQRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDLQRequest) ProtoMessage() {}

func (x *ListDLQRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_webhook_v1_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDLQRequest.ProtoReflect.Descriptor instead.
func (*ListDLQRequest) Descriptor() ([]byte, []int) {
	return file_api_webhook_v1_service_proto_rawDescGZIP(), []int{15}
}

func (x *ListDLQRequest) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *ListDLQRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListDLQResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of delivery attempts in the DLQ
	Dead          []*DeliveryAttempt `protobuf:"bytes,1,rep,name=dead,proto3" json:"dead,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDLQResponse) Reset() {
	*x = ListDLQResponse{}
	mi := &file_api_webhook_v1_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDLQResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDLQResponse) ProtoMessage() {}

func (x *ListDLQResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_webhook_v1_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDLQResponse.ProtoReflect.Descriptor instead.
func (*ListDLQResponse) Descriptor() ([]byte, []int) {
	return file_api_webhook_v1_service_proto_rawDescGZIP(), []int{16}
}

func (x *ListDLQResponse) GetDead() []*DeliveryAttempt {
	if x != nil {
		return x.Dead
	}
	return nil
}

var File_api_webhook_v1_service_proto protoreflect.FileDescriptor

const file_api_webhook_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1capi/webhook/v1/service.proto\x12\x0eapi.webhook.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a#openapi/openapiv3/annotations.proto\"\r\n" +
	"\vPingRequest\"(\n" +
	"\fPingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xa8\x01\n" +
	"\bEndpoint\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1a\n" +
	"\x03url\x18\x03 \x01(\tB\b\xbaH\x05r\x03\x88\x01\x01R\x03url\x12I\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampB\x0e\xbaH\v\xb2\x01\b2\x06\b\x80\x8bһ\x06R\tcreatedAt\"\xda\x01\n" +
	"\fSubscription\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12)\n" +
	"\vendpoint_id\x18\x04 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\n" +
	"endpointId\x12I\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampB\x0e\xbaH\v\xb2\x01\b2\x06\b\x80\x8bһ\x06R\tcreatedAt\"{\n" +
	"\x15CreateEndpointRequest\x12#\n" +
	"\ttenant_id\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\btenantId\x12\x1d\n" +
	"\x03url\x18\x02 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\x88\x01\x01R\x03url\x12\x1e\n" +
	"\x06secret\x18\x03 \x01(\tB\x06\xbaH\x03\xd8\x01\x01R\x06secret\"N\n" +
	"\x16CreateEndpointResponse\x124\n" +
	"\bendpoint\x18\x01 \x01(\v2\x18.api.webhook.v1.EndpointR\bendpoint\"\x95\x01\n" +
	"\x19CreateSubscriptionRequest\x12#\n" +
	"\ttenant_id\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\btenantId\x12%\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\teventType\x12,\n" +
	"\vendpoint_id\x18\x03 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\n" +
	"endpointId\"^\n" +
	"\x1aCreateSubscriptionResponse\x12@\n" +
	"\fsubscription\x18\x01 \x01(\v2\x1c.api.webhook.v1.SubscriptionR\fsubscription\"\xcd\x01\n" +
	"\x13PublishEventRequest\x12#\n" +
	"\ttenant_id\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\btenantId\x12%\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\teventType\x129\n" +
	"\apayload\x18\x03 \x01(\v2\x17.google.protobuf.StructB\x06\xbaH\x03\xc8\x01\x01R\apayload\x12/\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tB\x06\xbaH\x03\xd8\x01\x01R\x0eidempotencyKey\"i\n" +
	"\x14PublishEventResponse\x12&\n" +
	"\bevent_id\x18\x01 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\aeventId\x12)\n" +
	"\ffanout_count\x18\x02 \x01(\x05B\x06\xbaH\x03\xc8\x01\x01R\vfanoutCount\"\xd2\x05\n" +
	"\x0fDeliveryAttempt\x12)\n" +
	"\vdelivery_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\n" +
	"deliveryId\x12#\n" +
	"\bevent_id\x18\x02 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\aeventId\x12)\n" +
	"\vendpoint_id\x18\x03 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\n" +
	"endpointId\x12%\n" +
	"\treplay_of\x18\x04 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\breplayOf\x12=\n" +
	"\x06status\x18\x05 \x01(\x0e2%.api.webhook.v1.DeliveryAttemptStatusR\x06status\x12\x1f\n" +
	"\vhttp_status\x18\x06 \x01(\x05R\n" +
	"httpStatus\x12!\n" +
	"\ferror_reason\x18\a \x01(\tR\verrorReason\x12F\n" +
	"\venqueued_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampB\t\xbaH\x06\xd8\x01\x01\xb2\x01\x00R\n" +
	"enqueuedAt\x12F\n" +
	"\vdequeued_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampB\t\xbaH\x06\xd8\x01\x01\xb2\x01\x00R\n" +
	"dequeuedAt\x12>\n" +
	"\asent_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampB\t\xbaH\x06\xd8\x01\x01\xb2\x01\x00R\x06sentAt\x12H\n" +
	"\fdelivered_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampB\t\xbaH\x06\xd8\x01\x01\xb2\x01\x00R\vdeliveredAt\x12B\n" +
	"\tfailed_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampB\t\xbaH\x06\xd8\x01\x01\xb2\x01\x00R\bfailedAt\x12<\n" +
	"\x06dlq_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampB\t\xbaH\x06\xd8\x01\x01\xb2\x01\x00R\x05dlqAt\"\x80\x02\n" +
	"\x18GetDeliveryStatusRequest\x12&\n" +
	"\bevent_id\x18\x01 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\aeventId\x12,\n" +
	"\vendpoint_id\x18\x02 \x01(\tB\v\xbaH\b\xd8\x01\x01r\x03\xb0\x01\x01R\n" +
	"endpointId\x129\n" +
	"\x04from\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampB\t\xbaH\x06\xd8\x01\x01\xb2\x01\x00R\x04from\x125\n" +
	"\x02to\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampB\t\xbaH\x06\xd8\x01\x01\xb2\x01\x00R\x02to\x12\x1c\n" +
	"\x05limit\x18\x05 \x01(\x05B\x06\xbaH\x03\xd8\x01\x01R\x05limit\"X\n" +
	"\x19GetDeliveryStatusResponse\x12;\n" +
	"\battempts\x18\x01 \x03(\v2\x1f.api.webhook.v1.DeliveryAttemptR\battempts\"e\n" +
	"\x15ReplayDeliveryRequest\x12,\n" +
	"\vdelivery_id\x18\x01 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\n" +
	"deliveryId\x12\x1e\n" +
	"\x06reason\x18\x02 \x01(\tB\x06\xbaH\x03\xd8\x01\x01R\x06reason\"b\n" +
	"\x16ReplayDeliveryResponse\x12H\n" +
	"\vnew_attempt\x18\x01 \x01(\v2\x1f.api.webhook.v1.DeliveryAttemptB\x06\xbaH\x03\xc8\x01\x01R\n" +
	"newAttempt\"W\n" +
	"\x0eListDLQRequest\x12'\n" +
	"\vendpoint_id\x18\x01 \x01(\tB\x06\xbaH\x03\xd8\x01\x01R\n" +
	"endpointId\x12\x1c\n" +
	"\x05limit\x18\x02 \x01(\x05B\x06\xbaH\x03\xd8\x01\x01R\x05limit\"N\n" +
	"\x0fListDLQResponse\x12;\n" +
	"\x04dead\x18\x01 \x03(\v2\x1f.api.webhook.v1.DeliveryAttemptB\x06\xbaH\x03\xd8\x01\x01R\x04dead*\x81\x02\n" +
	"\x15DeliveryAttemptStatus\x12'\n" +
	"#DELIVERY_ATTEMPT_STATUS_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eDELIVERY_ATTEMPT_STATUS_QUEUED\x10\x01\x12%\n" +
	"!DELIVERY_ATTEMPT_STATUS_IN_FLIGHT\x10\x02\x12%\n" +
	"!DELIVERY_ATTEMPT_STATUS_DELIVERED\x10\x03\x12\"\n" +
	"\x1eDELIVERY_ATTEMPT_STATUS_FAILED\x10\x04\x12)\n" +
	"%DELIVERY_ATTEMPT_STATUS_DEAD_LETTERED\x10\x052\xf3\t\n" +
	"\x0eWebhookService\x12S\n" +
	"\x04Ping\x12\x1b.api.webhook.v1.PingRequest\x1a\x1c.api.webhook.v1.PingResponse\"\x10\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/v1/ping\x12\xc5\x01\n" +
	"\x0eCreateEndpoint\x12%.api.webhook.v1.CreateEndpointRequest\x1a&.api.webhook.v1.CreateEndpointResponse\"d\xbaG5\n" +
	"\tEndpoints\x1a(Register a new URL as a webhook endpoint\x82\xd3\xe4\x93\x02&:\x01*\"!/v1/tenants/{tenant_id}/endpoints\x12\xdf\x01\n" +
	"\x12CreateSubscription\x12).api.webhook.v1.CreateSubscriptionRequest\x1a*.api.webhook.v1.CreateSubscriptionResponse\"r\xbaG?\n" +
	"\rSubscriptions\x1a.Subscribe an endpoint to a specific event type\x82\xd3\xe4\x93\x02*:\x01*\"%/v1/tenants/{tenant_id}/subscriptions\x12\xb4\x01\n" +
	"\fPublishEvent\x12#.api.webhook.v1.PublishEventRequest\x1a$.api.webhook.v1.PublishEventResponse\"Y\xbaG%\n" +
	"\x06Events\x1a\x1bPublish a new webhook event\x82\xd3\xe4\x93\x02+:\x01*\"&/v1/tenants/{tenant_id}/events:publish\x12\xca\x01\n" +
	"\x11GetDeliveryStatus\x12(.api.webhook.v1.GetDeliveryStatusRequest\x1a).api.webhook.v1.GetDeliveryStatusResponse\"`\xbaG5\n" +
	"\x06Events\x1a+Get the delivery status of a specific event\x82\xd3\xe4\x93\x02\"\x12 /v1/events/{event_id}/deliveries\x12\xc2\x01\n" +
	"\x0eReplayDelivery\x12%.api.webhook.v1.ReplayDeliveryRequest\x1a&.api.webhook.v1.ReplayDeliveryResponse\"a\xbaG0\n" +
	"\n" +
	"Deliveries\x1a\"Replay a specific delivery attempt\x82\xd3\xe4\x93\x02(:\x01*\"#/v1/deliveries/{delivery_id}:replay\x12\x98\x01\n" +
	"\aListDLQ\x12\x1e.api.webhook.v1.ListDLQRequest\x1a\x1f.api.webhook.v1.ListDLQResponse\"L\xbaG:\n" +
	"\n" +
	"Deliveries\x1a,List all deliveries in the dead letter queue\x82\xd3\xe4\x93\x02\t\x12\a/v1/dlqB\x84\x03\xbaG\xb6\x02\n" +
	"\x053.0.0\x12m\n" +
	"\n" +
	"HarborHook\x12(A Go-first multi-tenant webhook platform\".\n" +
	"\fAustin Birch\x1a\x1eaustin@argus-entertainment.com2\x051.0.0:-\n" +
	"\tEndpoints\x12 Get data about webhook endpoints:5\n" +
	"\rSubscriptions\x12$Get data about webhook subscriptions:'\n" +
	"\x06Events\x12\x1dGet data about webhook events:/\n" +
	"\n" +
	"Deliveries\x12!Get data about webhook deliveriesZHgithub.com/austindbirch/harbor_hook/protogen/go/api/webhook/v1;webhookv1b\x06proto3"

var (
	file_api_webhook_v1_service_proto_rawDescOnce sync.Once
	file_api_webhook_v1_service_proto_rawDescData []byte
)

func file_api_webhook_v1_service_proto_rawDescGZIP() []byte {
	file_api_webhook_v1_service_proto_rawDescOnce.Do(func() {
		file_api_webhook_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_webhook_v1_service_proto_rawDesc), len(file_api_webhook_v1_service_proto_rawDesc)))
	})
	return file_api_webhook_v1_service_proto_rawDescData
}

var file_api_webhook_v1_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_webhook_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_api_webhook_v1_service_proto_goTypes = []any{
	(DeliveryAttemptStatus)(0),         // 0: api.webhook.v1.DeliveryAttemptStatus
	(*PingRequest)(nil),                // 1: api.webhook.v1.PingRequest
	(*PingResponse)(nil),               // 2: api.webhook.v1.PingResponse
	(*Endpoint)(nil),                   // 3: api.webhook.v1.Endpoint
	(*Subscription)(nil),               // 4: api.webhook.v1.Subscription
	(*CreateEndpointRequest)(nil),      // 5: api.webhook.v1.CreateEndpointRequest
	(*CreateEndpointResponse)(nil),     // 6: api.webhook.v1.CreateEndpointResponse
	(*CreateSubscriptionRequest)(nil),  // 7: api.webhook.v1.CreateSubscriptionRequest
	(*CreateSubscriptionResponse)(nil), // 8: api.webhook.v1.CreateSubscriptionResponse
	(*PublishEventRequest)(nil),        // 9: api.webhook.v1.PublishEventRequest
	(*PublishEventResponse)(nil),       // 10: api.webhook.v1.PublishEventResponse
	(*DeliveryAttempt)(nil),            // 11: api.webhook.v1.DeliveryAttempt
	(*GetDeliveryStatusRequest)(nil),   // 12: api.webhook.v1.GetDeliveryStatusRequest
	(*GetDeliveryStatusResponse)(nil),  // 13: api.webhook.v1.GetDeliveryStatusResponse
	(*ReplayDeliveryRequest)(nil),      // 14: api.webhook.v1.ReplayDeliveryRequest
	(*ReplayDeliveryResponse)(nil),     // 15: api.webhook.v1.ReplayDeliveryResponse
	(*ListDLQRequest)(nil),             // 16: api.webhook.v1.ListDLQRequest
	(*ListDLQResponse)(nil),            // 17: api.webhook.v1.ListDLQResponse
	(*timestamppb.Timestamp)(nil),      // 18: google.protobuf.Timestamp
	(*structpb.Struct)(nil),            // 19: google.protobuf.Struct
}
var file_api_webhook_v1_service_proto_depIdxs = []int32{
	18, // 0: api.webhook.v1.Endpoint.created_at:type_name -> google.protobuf.Timestamp
	18, // 1: api.webhook.v1.Subscription.created_at:type_name -> google.protobuf.Timestamp
	3,  // 2: api.webhook.v1.CreateEndpointResponse.endpoint:type_name -> api.webhook.v1.Endpoint
	4,  // 3: api.webhook.v1.CreateSubscriptionResponse.subscription:type_name -> api.webhook.v1.Subscription
	19, // 4: api.webhook.v1.PublishEventRequest.payload:type_name -> google.protobuf.Struct
	0,  // 5: api.webhook.v1.DeliveryAttempt.status:type_name -> api.webhook.v1.DeliveryAttemptStatus
	18, // 6: api.webhook.v1.DeliveryAttempt.enqueued_at:type_name -> google.protobuf.Timestamp
	18, // 7: api.webhook.v1.DeliveryAttempt.dequeued_at:type_name -> google.protobuf.Timestamp
	18, // 8: api.webhook.v1.DeliveryAttempt.sent_at:type_name -> google.protobuf.Timestamp
	18, // 9: api.webhook.v1.DeliveryAttempt.delivered_at:type_name -> google.protobuf.Timestamp
	18, // 10: api.webhook.v1.DeliveryAttempt.failed_at:type_name -> google.protobuf.Timestamp
	18, // 11: api.webhook.v1.DeliveryAttempt.dlq_at:type_name -> google.protobuf.Timestamp
	18, // 12: api.webhook.v1.GetDeliveryStatusRequest.from:type_name -> google.protobuf.Timestamp
	18, // 13: api.webhook.v1.GetDeliveryStatusRequest.to:type_name -> google.protobuf.Timestamp
	11, // 14: api.webhook.v1.GetDeliveryStatusResponse.attempts:type_name -> api.webhook.v1.DeliveryAttempt
	11, // 15: api.webhook.v1.ReplayDeliveryResponse.new_attempt:type_name -> api.webhook.v1.DeliveryAttempt
	11, // 16: api.webhook.v1.ListDLQResponse.dead:type_name -> api.webhook.v1.DeliveryAttempt
	1,  // 17: api.webhook.v1.WebhookService.Ping:input_type -> api.webhook.v1.PingRequest
	5,  // 18: api.webhook.v1.WebhookService.CreateEndpoint:input_type -> api.webhook.v1.CreateEndpointRequest
	7,  // 19: api.webhook.v1.WebhookService.CreateSubscription:input_type -> api.webhook.v1.CreateSubscriptionRequest
	9,  // 20: api.webhook.v1.WebhookService.PublishEvent:input_type -> api.webhook.v1.PublishEventRequest
	12, // 21: api.webhook.v1.WebhookService.GetDeliveryStatus:input_type -> api.webhook.v1.GetDeliveryStatusRequest
	14, // 22: api.webhook.v1.WebhookService.ReplayDelivery:input_type -> api.webhook.v1.ReplayDeliveryRequest
	16, // 23: api.webhook.v1.WebhookService.ListDLQ:input_type -> api.webhook.v1.ListDLQRequest
	2,  // 24: api.webhook.v1.WebhookService.Ping:output_type -> api.webhook.v1.PingResponse
	6,  // 25: api.webhook.v1.WebhookService.CreateEndpoint:output_type -> api.webhook.v1.CreateEndpointResponse
	8,  // 26: api.webhook.v1.WebhookService.CreateSubscription:output_type -> api.webhook.v1.CreateSubscriptionResponse
	10, // 27: api.webhook.v1.WebhookService.PublishEvent:output_type -> api.webhook.v1.PublishEventResponse
	13, // 28: api.webhook.v1.WebhookService.GetDeliveryStatus:output_type -> api.webhook.v1.GetDeliveryStatusResponse
	15, // 29: api.webhook.v1.WebhookService.ReplayDelivery:output_type -> api.webhook.v1.ReplayDeliveryResponse
	17, // 30: api.webhook.v1.WebhookService.ListDLQ:output_type -> api.webhook.v1.ListDLQResponse
	24, // [24:31] is the sub-list for method output_type
	17, // [17:24] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_api_webhook_v1_service_proto_init() }
func file_api_webhook_v1_service_proto_init() {
	if File_api_webhook_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_webhook_v1_service_proto_rawDesc), len(file_api_webhook_v1_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_webhook_v1_service_proto_goTypes,
		DependencyIndexes: file_api_webhook_v1_service_proto_depIdxs,
		EnumInfos:         file_api_webhook_v1_service_proto_enumTypes,
		MessageInfos:      file_api_webhook_v1_service_proto_msgTypes,
	}.Build()
	File_api_webhook_v1_service_proto = out.File
	file_api_webhook_v1_service_proto_goTypes = nil
	file_api_webhook_v1_service_proto_depIdxs = nil
}
